# Generated by Django 5.2.3 on 2025-07-01 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_faculty_course_faculty_user_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('class_code', models.CharField(max_length=100, unique=True, verbose_name='Mã lớp sinh hoạt')),
                ('year_of_admission', models.IntegerField(verbose_name='Năm nhập học')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.faculty', verbose_name='Khoa')),
            ],
            options={
                'verbose_name': 'Lớp sinh hoạt',
                'verbose_name_plural': 'Các lớp sinh hoạt',
                'ordering': ['class_code'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='administrative_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.administrativeclass', verbose_name='Lớp sinh hoạt'),
        ),
    ]
