# Generated by Django 5.2.3 on 2025-06-26 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('course_code', models.CharField(max_length=20, unique=True, verbose_name='Mã học phần')),
                ('course_name', models.CharField(max_length=255, verbose_name='Tên học phần')),
                ('credits', models.IntegerField(verbose_name='Số tín chỉ')),
            ],
            options={
                'verbose_name': 'Học phần',
                'verbose_name_plural': 'Các học phần',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('room_code', models.CharField(max_length=50, unique=True, verbose_name='Mã phòng')),
                ('building', models.CharField(max_length=50, verbose_name='Tòa nhà')),
                ('geo_latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Vĩ độ')),
                ('geo_longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Kinh độ')),
                ('wifi_ssid', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên Wifi')),
            ],
            options={
                'verbose_name': 'Phòng học',
                'verbose_name_plural': 'Các phòng học',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('user_code', models.CharField(max_length=20, unique=True, verbose_name='Mã người dùng (MSSV/MSGV)')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('role', models.CharField(choices=[('student', 'Sinh viên'), ('instructor', 'Giảng viên'), ('admin', 'Quản trị viên')], default='student', max_length=20, verbose_name='Vai trò')),
                ('face_embedding', models.TextField(blank=True, null=True, verbose_name='Vector đặc trưng khuôn mặt')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Là nhân viên')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Người dùng',
                'verbose_name_plural': 'Người dùng',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('class_code', models.CharField(max_length=50, unique=True, verbose_name='Mã lớp học phần')),
                ('academic_year', models.CharField(max_length=20, verbose_name='Năm học')),
                ('semester', models.CharField(max_length=20, verbose_name='Học kỳ')),
                ('instructor', models.ForeignKey(blank=True, limit_choices_to={'role': 'instructor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_classes', to=settings.AUTH_USER_MODEL, verbose_name='Giảng viên chính')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.course', verbose_name='Học phần')),
            ],
            options={
                'verbose_name': 'Lớp học phần',
                'verbose_name_plural': 'Các lớp học phần',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('group_code', models.CharField(default='Lý thuyết', max_length=50, verbose_name='Nhóm (LT/TH)')),
                ('schedule_type', models.CharField(choices=[('RECURRING', 'Lịch cố định'), ('ONE_TIME', 'Lịch một lần (học bù)')], default='RECURRING', max_length=20)),
                ('schedule_date', models.DateField(blank=True, null=True, verbose_name='Ngày học (cho lịch 1 lần)')),
                ('day_of_week', models.IntegerField(blank=True, choices=[(2, 'Thứ Hai'), (3, 'Thứ Ba'), (4, 'Thứ Tư'), (5, 'Thứ Năm'), (6, 'Thứ Sáu'), (7, 'Thứ Bảy'), (8, 'Chủ Nhật')], null=True, verbose_name='Thứ trong tuần')),
                ('start_time', models.TimeField(verbose_name='Giờ bắt đầu')),
                ('end_time', models.TimeField(verbose_name='Giờ kết thúc')),
                ('class_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.class', verbose_name='Lớp học phần')),
                ('instructor', models.ForeignKey(blank=True, limit_choices_to={'role': 'instructor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules_in_charge', to=settings.AUTH_USER_MODEL, verbose_name='Người phụ trách')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.room', verbose_name='Phòng học')),
            ],
            options={
                'verbose_name': 'Lịch học',
                'verbose_name_plural': 'Các lịch học',
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('status', models.CharField(choices=[('PRESENT', 'Có mặt'), ('ABSENT', 'Vắng'), ('LATE', 'Đi trễ'), ('EXCUSED', 'Vắng có phép')], default='ABSENT', max_length=20, verbose_name='Trạng thái')),
                ('check_in_time', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian điểm danh')),
                ('recorded_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('recorded_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('auth_methods', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phương thức xác thực')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sinh viên')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.schedule', verbose_name='Buổi học')),
            ],
            options={
                'verbose_name': 'Bản ghi điểm danh',
                'verbose_name_plural': 'Các bản ghi điểm danh',
            },
        ),
        migrations.CreateModel(
            name='AbsenceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('reason', models.TextField(verbose_name='Lý do')),
                ('proof_url', models.CharField(blank=True, max_length=512, null=True, verbose_name='Link minh chứng')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ duyệt'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Từ chối')], default='PENDING', max_length=20)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.schedule')),
            ],
            options={
                'verbose_name': 'Đơn xin phép vắng',
                'verbose_name_plural': 'Các đơn xin phép vắng',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('status', models.CharField(default='Enrolled', max_length=20, verbose_name='Trạng thái')),
                ('class_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.class', verbose_name='Lớp học phần')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sinh viên')),
            ],
            options={
                'verbose_name': 'Sinh viên ghi danh',
                'verbose_name_plural': 'Danh sách sinh viên ghi danh',
                'unique_together': {('student', 'class_instance')},
            },
        ),
    ]
