# Generated by Django 5.2.3 on 2025-06-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_fcm_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absencerequest',
            name='proof_url',
        ),
        migrations.AddField(
            model_name='absencerequest',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to='absence_proofs/', verbose_name='File minh chứng'),
        ),
    ]
