# Generated by Django 5.2.3 on 2025-07-01 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_security_indexes'),
        ('core', '0006_administrativeclass_user_administrative_class'),
    ]

    operations = [
    ]
