version: '3.8'  
  
services:  
  db:  
    image: postgres:15  
    environment:  
      POSTGRES_DB: mfa_attendance_db  
      POSTGRES_USER: postgres  
      POSTGRES_PASSWORD: password  
    volumes:  
      - postgres_data:/var/lib/postgresql/data  
    ports:  
      - "5432:5432"  
  
  redis:  
    image: redis:7-alpine  
    ports:  
      - "6379:6379"  
  
  web:  
    build: ./mfa_project  
    command: python manage.py runserver 0.0.0.0:8000  
    volumes:  
      - ./mfa_project:/app  
    ports:  
      - "8000:8000"  
    depends_on:  
      - db  
      - redis  
    environment:  
      - DEBUG=1  
      - DATABASE_URL=postgresql://postgres:password@db:5432/mfa_attendance_db  
      - REDIS_URL=redis://redis:6379/1  
  
  celery:  
    build: ./mfa_project  
    command: celery -A mfa_attendance_project worker -l info  
    volumes:  
      - ./mfa_project:/app  
    depends_on:  
      - db  
      - redis  
    environment:  
      - DEBUG=1  
      - DATABASE_URL=postgresql://postgres:password@db:5432/mfa_attendance_db  
      - REDIS_URL=redis://redis:6379/1  
  
volumes:  
  postgres_data: