// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCHdD64cc_wxInz93aAD32Cy255HYuaM4',
    appId: '1:418800992807:web:71413c1d2638b421230402',
    messagingSenderId: '418800992807',
    projectId: 'ctut-attendance-system',
    authDomain: 'ctut-attendance-system.firebaseapp.com',
    storageBucket: 'ctut-attendance-system.firebasestorage.app',
    measurementId: 'G-P1CFNH2CLN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk08sX4CjIozRMRQN7qLljy3Zhtd89asY',
    appId: '1:418800992807:android:375674da1d31cf19230402',
    messagingSenderId: '418800992807',
    projectId: 'ctut-attendance-system',
    storageBucket: 'ctut-attendance-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqKxcK2xrUzAkJx_qZ4qZLM2S4-a0fJes',
    appId: '1:418800992807:ios:326b309cdcce2a69230402',
    messagingSenderId: '418800992807',
    projectId: 'ctut-attendance-system',
    storageBucket: 'ctut-attendance-system.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqKxcK2xrUzAkJx_qZ4qZLM2S4-a0fJes',
    appId: '1:418800992807:ios:326b309cdcce2a69230402',
    messagingSenderId: '418800992807',
    projectId: 'ctut-attendance-system',
    storageBucket: 'ctut-attendance-system.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCHdD64cc_wxInz93aAD32Cy255HYuaM4',
    appId: '1:418800992807:web:01e3805c6c4a5399230402',
    messagingSenderId: '418800992807',
    projectId: 'ctut-attendance-system',
    authDomain: 'ctut-attendance-system.firebaseapp.com',
    storageBucket: 'ctut-attendance-system.firebasestorage.app',
    measurementId: 'G-VZJWWNE0EV',
  );
}
