"""
Django settings for mfa_attendance_project project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-bi=gv#maj2qq5=noeds126$z4g1%g78icj59mu79yh96k017t%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'django_filters',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.SecurityHeadersMiddleware',
    'core.middleware.AttendanceAuditMiddleware',
]

ROOT_URLCONF = 'mfa_attendance_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mfa_attendance_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'mfa_attendance_db',
        'USER': 'postgres',
        'PASSWORD': 'admin123',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'core.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

from datetime import timedelta

SIMPLE_JWT = {  
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=2),  # Tăng từ 5 phút lên 2 giờ  
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),  # Tăng từ 1 ngày lên 7 ngày  
    "ROTATE_REFRESH_TOKENS": True,  # Tự động tạo refresh token mới  
    "BLACKLIST_AFTER_ROTATION": True,  # Blacklist refresh token cũ  
    "UPDATE_LAST_LOGIN": True,  
    "ALGORITHM": "HS256",  
    "SIGNING_KEY": SECRET_KEY,  
    "VERIFYING_KEY": None,  
    "AUDIENCE": None,  
    "ISSUER": None,  
    "JWK_URL": None,  
    "LEEWAY": 0,  
      
    "AUTH_HEADER_TYPES": ("Bearer",),  
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",  
    "USER_ID_FIELD": "id",  
    "USER_ID_CLAIM": "user_id",  
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",  
  
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),  
    "TOKEN_TYPE_CLAIM": "token_type",  
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",  
  
    "JTI_CLAIM": "jti",  
    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",  
    "SLIDING_TOKEN_LIFETIME": timedelta(hours=2),  
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=7),  

    # Thêm dòng này để sử dụng serializer tùy chỉnh  
    "TOKEN_OBTAIN_PAIR_SERIALIZER": "core.token_serializers.MyTokenObtainPairSerializer", 
}

# Cấu hình cache cho rate limiting  
CACHES = {  
    'default': {  
        'BACKEND': 'django_redis.cache.RedisCache',  
        'LOCATION': 'redis://127.0.0.1:6379/1',  
        'OPTIONS': {  
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',  
        }  
    }  
}  
  
# Cấu hình logging cho audit trail  
LOGGING = {  
    'version': 1,  
    'disable_existing_loggers': False,  
    'formatters': {  
        'verbose': {  
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',  
            'style': '{',  
        },  
        'simple': {  
            'format': '{levelname} {message}',  
            'style': '{',  
        },  
    },  
    'handlers': {  
        'file': {  
            'level': 'INFO',  
            'class': 'logging.FileHandler',  
            'filename': 'logs/security.log',  
            'formatter': 'verbose',  
        },  
        'console': {  
            'level': 'DEBUG',  
            'class': 'logging.StreamHandler',  
            'formatter': 'simple',  
        },  
    },  
    'loggers': {  
        'core.middleware': {  
            'handlers': ['file', 'console'],  
            'level': 'INFO',  
            'propagate': True,  
        },  
    },  
}

# Cấu hình bảo mật Django  
SECURE_BROWSER_XSS_FILTER = True  
SECURE_CONTENT_TYPE_NOSNIFF = True  
SECURE_HSTS_SECONDS = 31536000  # 1 năm  
SECURE_HSTS_INCLUDE_SUBDOMAINS = True  
SECURE_HSTS_PRELOAD = True  
  
# File upload security  
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB  
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB  
FILE_UPLOAD_PERMISSIONS = 0o644  
  
# Session security  
SESSION_COOKIE_SECURE = True  # Chỉ gửi cookie qua HTTPS  
SESSION_COOKIE_HTTPONLY = True  # Không cho phép JavaScript truy cập cookie  
SESSION_COOKIE_SAMESITE = 'Strict'  
CSRF_COOKIE_SECURE = True  
CSRF_COOKIE_HTTPONLY = True  
CSRF_COOKIE_SAMESITE = 'Strict'  

# Cấu hình cho logic điểm danh (cập nhật)  
ATTENDANCE_SETTINGS = {  
    'GPS_DISTANCE_TOLERANCE_METERS': 100,  
    'FACE_RECOGNITION_TOLERANCE': 0.5,  
    'QR_TOKEN_LIFETIME_MINUTES': 5,  
    'MAX_ATTENDANCE_ATTEMPTS_PER_WINDOW': 3,  
    'ATTENDANCE_RATE_LIMIT_WINDOW_MINUTES': 15,  
    'MAX_FACE_REGISTRATION_ATTEMPTS_PER_WINDOW': 5,  
    'FACE_REGISTRATION_RATE_LIMIT_WINDOW_MINUTES': 60,
    'LIVENESS_MIN_BLINKS': 1,  # Số lần nháy mắt tối thiểu  
    'LIVENESS_MIN_BLINK_FRAMES': 2,  # Số frame tối thiểu cho mắt đóng  
    'LIVENESS_MIN_OPEN_FRAMES': 3,   # Số frame tối thiểu cho mắt mở  
}

# Cấu hình Firebase
import os
FIREBASE_CREDENTIALS_PATH = os.path.join(BASE_DIR, 'firebase-credentials.json')

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000", # Địa chỉ của ứng dụng React
]

# Cấu hình cho việc upload file của người dùng
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# In email ra console thay vì gửi thật
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Cấu hình Celery
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# Google OAuth2 Configuration
GOOGLE_OAUTH2_CLIENT_ID = '418800992807-0rt8e8q76t6fmj0o95cucqsalhr9cmlv.apps.googleusercontent.com'
# Danh sách các domain được phép
ALLOWED_EMAIL_DOMAINS = ['student.ctuet.edu.vn', 'ctuet.edu.vn']